# Use root/example as user/password credentials
version: '3.1'

services:
  backend:
    build: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    ports:
      - 3050:3050
    networks:
      - express-mongo
      - express-react

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    ports:
      - 27017:27017

  frontend:
    build: frontend
    volumes: 
      - ./frontend:/usr/src/app
      # - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - 3001:3000
    networks:
      - express-react

networks:
  express-mongo:
  express-react: